"""Rename field date_to.

Revision ID: 29e6859dbd41
Revises: 2eb428ad6154
Create Date: 2023-10-11 16:02:42.815647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e6859dbd41'
down_revision: Union[str, None] = '2eb428ad6154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('created_at', sa.Date(), nullable=False))
    op.drop_column('question', 'date_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('question', 'created_at')
    # ### end Alembic commands ###
