version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./app/
    env_file: .env
    depends_on:
      - db
    command: ["docker/app.sh"]
